# Basic settings
set -s copy-command 'xsel -i'
set -as terminal-features ',rxvt-unicode-256color:clipboard'
set -ga terminal-overrides ",*:RGB"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi
set-option -g renumber-windows on

set -g status-position bottom
set -g status-left-length 100
set -g status-left " #[bold] #S #[nobold]|"
set -g window-status-current-format "#[bold] ✓#[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g extended-keys on
set -g focus-events on
set -g mouse on
set -g escape-time 0
set -g default-terminal "tmux-256color"
